<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
<title>Sequence Manipulation Suite</title>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />

<style type="text/css">
body.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}
div.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}
div.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}
div.info {font-weight: bold}
span.ident {color: #FFFFFF; background-color: #000000}
span.sim {color: #FFFFFF; background-color: #666666}
span.g, span.a, span.v, span.l, span.i {color: #000000; background-color: #C0C0C0}
span.f, span.y, span.w {color: #000000; background-color: #FF6600}
span.c, span.m {color: #000000; background-color: #FFFF00}
span.s, span.t {color: #000000; background-color: #66FF00}
span.k, span.r, span.h {color: #000000; background-color: #FF0000}
span.d, span.e {color: #000000; background-color: #0066FF}
span.n, span.q {color: #000000; background-color: #996633}
span.p {color: #000000; background-color: #FF99FF}
</style>

</head>
<body class="main">
<div class="title">Ident and Sim results</div>

<pre>
<div class="pre">
<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CremaneiFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 483

Identical residues: 483

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CremaneiFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 483

Identical residues: 483

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CremaneiFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 483

Identical residues: 483

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CremaneiFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 483

Identical residues: 483

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CelegansFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CelegansFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 449

Identical residues: 449

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CelegansFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CelegansFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 449

Identical residues: 449

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CelegansFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CelegansFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 449

Identical residues: 449

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CelegansFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CelegansFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 449

Identical residues: 449

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CbriggsaeFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 502

Identical residues: 502

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CbriggsaeFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CbriggsaeFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 502

Identical residues: 502

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CbriggsaeFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CbriggsaeFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 502

Identical residues: 502

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CbriggsaeFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CbriggsaeFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 502

Identical residues: 502

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CremaneiFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 483

Identical residues: 483

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CremaneiFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 483

Identical residues: 483

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CremaneiFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 483

Identical residues: 483

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CelegansFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CelegansFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 449

Identical residues: 449

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CelegansFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CelegansFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 449

Identical residues: 449

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CelegansFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CelegansFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 449

Identical residues: 449

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CbriggsaeFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 502

Identical residues: 502

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CbriggsaeFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CbriggsaeFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 502

Identical residues: 502

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CbriggsaeFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CbriggsaeFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 502

Identical residues: 502

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CremaneiFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 483

Identical residues: 483

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CremaneiFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 483

Identical residues: 483

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CelegansFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CelegansFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 449

Identical residues: 449

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CelegansFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CelegansFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 449

Identical residues: 449

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CbriggsaeFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 502

Identical residues: 502

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CbriggsaeFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CbriggsaeFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 502

Identical residues: 502

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CremaneiFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 483

Identical residues: 483

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CelegansFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CelegansFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 449

Identical residues: 449

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CremaneiFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CbriggsaeFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



<b>Results for CbriggsaeFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 502

Identical residues: 502

  Similar residues: 0

  Percent identity: 100.00

Percent similarity: 100.00



<b>Results for CremaneiFEM-2 vs CelegansFEM-2:</b>

  Alignment length: 485

Identical residues: 279

  Similar residues: 63

  Percent identity: 57.53

Percent similarity: 70.52



<b>Results for CremaneiFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 505

Identical residues: 287

  Similar residues: 58

  Percent identity: 56.83

Percent similarity: 68.32



<b>Results for CelegansFEM-2 vs CbriggsaeFEM-2:</b>

  Alignment length: 504

Identical residues: 275

  Similar residues: 62

  Percent identity: 54.56

Percent similarity: 66.87



</div>
</pre>

</body>
</html>

